name: NuxNoobs
main: com.bukkit.N4th4.NuxNoobs.NuxNoobs
version: 1.4
commands:
    nuxnoobs:
        description: All of the NuxNoobs commands
        usage: Command unrecognised by NuxNoobs. Use /NuxNoobs help.
